package terminalmenu

//go:generate stringer -type DictionaryKey -linecomment -output dictionary_string.go

// DictionaryKey represents a dictionary key
type DictionaryKey byte

const (
	DictionaryKeyBack         DictionaryKey = iota // Back
	DictionaryKeyExit                              // Exit
	DictionaryKeyAskForNumber                      // What to do?:
	DictionaryKeyEnterPrompt                       // Press ENTER to continue...
)

// Dictionary is a set of strings declaring a set of strings autogenerated by menu.
// you can edit them in (*Menu).ChangeDictionaryDef
type Dictionary map[DictionaryKey]string

func createDictionary() Dictionary {
	result := make(Dictionary)

	for i := DictionaryKeyBack; i <= DictionaryKeyEnterPrompt; i++ {
		result[i] = i.String()
	}

	return result
}
